README.md, setup.py, wplay/savechat.py, wplay/wplay.py
- the initial script for savechat script
- updating ideas in the readme file
- created option for savechat
=> new changes

README.md
Add a new functionality, keep a record of states of multiple users in csv, for further analysis
=> Add new functionality

wplay/locationfinder.py
finding location by ip address is done in this pull request
=> location finder initial files

wplay/savechat.py
This is fix for a typo in savechat.py - not changing it results in error
=> fix_bs4_typo

wplay/onlinetracker.py
=> save in another directory inside wplay

setup.py
Added Playsound in setup file. Thanks
=> Added Playsound in Setup file

wplay/tgbot.py
=> add code for telegram bot

README.md, wplay/savechat.py, wplay/settings.cfg, wplay/wplay.py
These codes are taken from https://github.com/EliteAndroidApps/WhatsApp-GD-Extractor.
These scripts download the WhatsApp backup from your google drive and save the encrypted form of that backup.
=> saves all chat

wplay/onlinetracker.py, wplay/tgbot.py
=> added telegram message facility

wplay/wplay.py
=> corrected wtb option

setup.py, wplay/seleniumUtils.py, wplay/tgbot.py
=> added sleep before click in person

wplay/wplay.py
=> Added a beauty  figlet

wplay/__main__.py, wplay/messageblast.py, wplay/messagetimer.py, wplay/onlinetracker.py, wplay/tgbot.py, wplay/utils/TODO, wplay/utils/helpers.py, wplay/utils/pyppeteerConfig.py, wplay/utils/pyppeteerSearch.py, wplay/utils/sessionManagment.py, wplay/wchat.py
Fixed: #116
Fixed: #112 
Fixed: #113
Fixed: #110 
Fixed: #109
=> Bug Fixes and Refactoration

requirements.txt, wplay/utils/session_manager.py
**Changes Made:**
Used [Transitions Library](https://pypi.org/project/transitions/), in future the menu may become lengthy, so this library will be helpful in viewing states and transition visually.
Removed recursion
**Fixes/Issues:**
fixed issue #149
=> Refactorized session management and removed recursion

wplay/utils/helpers.py, wplay/utils/target_search.py
Gets the following information about a selected target contact:
1. name
2. last seen
3. phone
4. about
5. groups in common
=> #144-Get target info

wplay/__main__.py, wplay/messageblast.py, wplay/messagetimer.py, wplay/onlinetracker.py, wplay/savechat.py, wplay/scheduleMessage.py, wplay/tgbot.py, wplay/utils/Logger.py, wplay/utils/browser_config.py, wplay/utils/io.py, wplay/utils/session_manager.py, wplay/utils/target_data.py, wplay/utils/target_search.py, wplay/wchat.py
#143 I have added type annotations according to python 3 to make this code more readable.
=> #143 type annotations added according to python3

wplay/__main__.py, wplay/changeAbout.py, wplay/utils/helpers.py
Fixes #86
This script changes the about section of your whatsapp account. You can change the about once in every second or once in 30 min. 
**The script fetches an api that gives the total coronavirus cases around the globe and changes your about section with that.**
How to use:
> python3 -m wplay -wabt OR python3 -m wplay --wabout
You then need to give a choice to either change your about in 1 sec or 30 min
=> Change About section

CODE_OF_CONDUCT.md, CodeOfConduct.md
Closes: #253  (issue number)
Added CODE_OF_CONDUCT.md file.
@rpotter12  Please review it and do let me know if any changes are required.
=> Added CODE_OF_CONDUCT.md

README.md, wplay/__main__.py, wplay/changeAbout.py, wplay/wnews.py
Closes: #80 
This script gives news in the target whatsapp group. Currently the news is basically live corona virus news. The user needs to specify country code. After that the script gives live updates of corona virus on that particular country after every 15 minutes
Run `python3 -m wplay -wnews "Anyname"`
=> News(idea) #80 resolved

requirements.txt
Updated requirements.txt file with newsapi and dotenv packages.
Do pip install -r requirements.txt to install packages
=> updated requirements.txt to include newsapi and dotenv package

wplay/messageblast.py, wplay/messagetimer.py, wplay/onlinetracker.py, wplay/utils/target_search.py, wplay/wchat.py
Closes #82 
Added functionality to get phone number of all contacts in new target search method.
Added reloading of page before new target search method is called in case of exception
=> #82 get number of all targets

tests/test_logger.py
102
test_logger.py file added in tests folder 
A Log file is created using Logger class in Logger.py and the log is tested in two ways.
1. The logfile is checked if its created and exists on right path.
2. Class LoggingTestCase, which inherits from unittest.TestCase. For every test run, logs are automatically captured to self.captured_logs. If the test fails, the contents of self.captured_logs are written to the test output for easy debugging. Using assertLogs to test that at least one message is logged on the logger or one of its children, with at least the given level. Then using asserEqual to compare the file content.
A python file added in tests folder
_Put an `x` in the boxes …
=> Automated unit test case added for Logger.py successfully.

wplay/__main__.py, wplay/utils/Logger.py, wplay/utils/helpers.py
https://github.com/rpotter12/whatsapp-play/issues/280
bugfix: log file wasn't created automatically, added a verification in Logger class.
- [ x] Bugfix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project
=> bugfix: log file not exist

wplay/utils/target_search.py
Closes: #283 
This PR adds a check that ensures that the contact name entered exists in the user's address book. If it does not, the program will issue a message asking to enter a valid contact name  and then exit
- [ x] Bugfix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
=> added check to see if contact name entered is valid, if not, program exits 

Dockerfile
#21
#21
Dockerfile added
Dockerfile has been written which creates an image of 440 MB.
Alpine has been used all the installations has been taken care of all commands are added according to alpine and python3
=> #21 Fix21docker image

wplay/__main__.py, wplay/about_changer.py, wplay/get_media.py, wplay/get_news.py, wplay/message_blast.py, wplay/message_timer.py, wplay/online_tracker.py, wplay/save_chat.py, wplay/schedule_message.py, wplay/telegram_bot.py, wplay/terminal_chat.py, wplay/utils/Logger.py, wplay/utils/SessionManager.py, wplay/utils/browser_config.py, wplay/utils/helpers.py, wplay/utils/io.py, wplay/utils/target_data.py, wplay/utils/target_search.py, wplay/utils/target_select.py
=> [WIP] followed by PEP8

tests/test_helpers.py, tests/test_kill_child_process.py, tests/test_logger.py, wplay/__main__.py, wplay/utils/Logger.py, wplay/utils/helpers.py
#102 
1.test_kill_child_process.py-Updated according to current kill_process file
2.helper.py-test_log_file_path added to test logger class
3.test_helper.py-test_log_file_path existence checked
4.Logger.py-(i) Format of the logger is changed asc time is removed as it was not possible to 
check the content of log file with this format
(ii)testwplay.log file is created and updated according to the current logger class
5.test_logger.py-Test is changed to the current format of the logger class.
6.wplay/main-EOL error fixed using multiline string
All are running successfully and updated according to the current format of the project.
Test files changed, the test log file created path added and EOL error removed
_Put an `x` …
=> All Test files updated according to updated logger class and helper file.

README.md, setup.py, wplay/__main__.py, wplay/broadcast_message.py, wplay/message_service.py, wplay/utils/MessageStack.py, wplay/utils/helpers.py, wplay/utils/target_search.py, wplay/utils/verify_internet.py
It's a substitute for the API, allow you to communicate your programs to wplay. You modify our file messages.json with the number and message and the service will read the JSON and send the message.
I also fixed the alerts that appeared and prevented the broadcast from working.
=> Feature message_service

.travis.yml
#20 
.travis.yml file added
The file is added according to correct versions and unit test commands
A file named .travis.yml is created in whatsapp-play-master folder and it's configured properly.
I would request you to let this issue open as I am working on codecov script for continuous testing.
Any other information that is important to this pull request.
=> .travis.yml file added successfully

.travis.yml, tests/test_helpers.py
#20 
.travis.yml file is successfully build
I am working on codecov script I would request you to let this issue remain open.
=> Successfully Build travis on Travis CI

.travis.yml
#20 
#20 
script added to see code coverage on codecov.io Cureent coverage is 72.83%.Current file successfully build Travis CI and codecov but two lines have {16,20} to build only travis.yml file.
=> Codecov script added successfully for coverage in travis.yml file

tests/test_helpers.py, wplay/__main__.py, wplay/download_media.py, wplay/utils/helpers.py
Closes: #84 
This PR will let users download media from one contact
How to use: `python -m wplay -wd AnyName` or `python -m wplay --download_media AnyName`
Input number of media to be downloaded.
=> download media

wplay/chatbot.py, wplay/terminal_chat.py
#128 
Chatbot added successfully.Initially basic commands like hi, how are you ? , good morning , good night and help. More commands can be added as per requirement.The target needs to send the message stating with"/" and then the chatbot is automatically activated and replies goes itself to the target.
I want to add few more features like doing google search or images So I would request to keep this issue open.Initial files have been added successfully.
=> Chatbot added successfully

wplay/terminal_chat.py, wplay/utils/helpers.py
=> fix travis build error

wplay/chatbot.py, wplay/terminal_chat.py, wplay/utils/helpers.py
#330 
The target can write /image {query} and the bot will automatically search google images for the query and save that image in wplay/chatbotImages folder.Now the user will automatically be redirected to choose file user can choose the then the image screenshot is sent to the target. The function has been made compatible with pyppeteer the browser is open seacges google image takes screenshot and saves it.
The screenshot saved in wplay/chatbotfolder
User redirected automatically to choose file
=> Google search for image sends screenshot of webpage successfully added.

README.md, wplay/get_news.py
#345 
#345 
First I resolved the issue of local variable 'news_' referenced before assignment but after that, it gave another error due to the wrong assignment of API Key I got my API key entered but didn't. I have removed unwanted imports and decreased complexity. I have resolved all issues regarding -wgn command now working successfully.
Running Successfully
=> get_news working successfully now.

wplay/chatbot.py
#330 
User needs to type /maps {origin},{destionation},{travel mode} and a link will be replied by the bot by which clicking on it will redirect the user to google maps auto filled source dest and travel mode.If google maps is not installed then it will open in browser.
After clicking on link
=> Google maps feature added to chatbot successfully.

README.md, wplay/about_changer.py
#347 
#347 
Error removed command working successfully and changing about now. Also readme has been updated correctly. 
=> -wa command working successfully now

requirements.txt, wplay/save_chat.py, wplay/terminal_chat.py, wplay/text_to_speech.py, wplay/utils/helpers.py, wplay/utils/io.py
#271 
#271 
Using gTTs library I have implemented text to speech. The user can enter the text an audio file will be saved in wplay/audioFiles. The user can use this feature in chatting, message-schedule, and message blast. The user has to type command #_TTS then the user has to enter the text it wants to convert to audio file then a list of languages supported will be printed it can enter the code. There also many more language option available but I have added some common and all Indian languages. Then the audio file will be saved and automatically the file attachment option will open the user can select the file and it will be sent.
Please …
=> Text to speech added successfully.

wplay/__main__.py, wplay/chat_intermediator.py, wplay/terminal_chat.py
I have changed nargs for target back to '?' and added new for intermediate i.e. -s and -r. Now everything is working fine.
=> Comman line argument error resolved

wplay/terminal_chat.py
#334 
#334
I have removed the error now last message can be seen in both chats of target and group as well.
- [] New feature (non-breaking change which adds functionality)
=> last msg received in group

wplay/utils/helpers.py, wplay/utils/target_select.py
Fix broken selectors of manual target select and online tracker
Fix broken selectors
=> fixed selectors of manual target select

wplay/broadcast_message.py, wplay/chat_intermediator.py, wplay/chatbot.py, wplay/get_media.py, wplay/get_news.py, wplay/message_blast.py, wplay/message_timer.py, wplay/online_tracker.py, wplay/save_chat.py, wplay/schedule_message.py, wplay/telegram_bot.py, wplay/terminal_chat.py, wplay/utils/helpers.py, wplay/utils/target_search.py, wplay/utils/verify_internet.py
- Add docstrings
- Remove unused variables.
=> add docstrings and remove unused variable

.circleci/config.yml, .travis.yml
=> Fix circle ci build

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Update issue templates (#406)

.github/workflows/pylint.yml
=> Pylint workflow
